# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='media/account/media/user_images/default.jpg', upload_to='media/account/media/user_images')),
                ('date_of_birth', models.DateField(default='1212-12-12', null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('N', 'Not specified'), ('M', 'Male')], default='N', max_length=1, null=True)),
                ('country', models.CharField(default='Country of origin', max_length=30, null=True)),
                ('about', models.TextField(default='about me', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
