# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('N', 'Not specified'), ('M', 'Male')], default='N', max_length=1, null=True),
        ),
    ]
