# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_data_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_image',
            field=models.ImageField(default='static/user_images/default.jpg', upload_to='static/user_images'),
        ),
    ]
