# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160518_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
