# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160527_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
