# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160527_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='about',
            field=models.TextField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='country',
            field=models.CharField(blank='True', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='date_of_birth',
            field=models.DateField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.CharField(blank='True', choices=[('F', 'Female'), ('N', 'Not specified'), ('M', 'Male')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_image',
            field=models.ImageField(blank='True', default='account/media/user_images/default.jpg', upload_to='account/media/user_images'),
        ),
    ]
