# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160530_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_image',
            field=models.ImageField(blank='True', default='account/media/user_images/default.jpg', null='True', upload_to='account/media/user_images'),
        ),
    ]
