# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160518_1145'),
        ('account', '0011_auto_20160531_0828'),
    ]

    operations = [
    ]
