# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('N', 'Not specified'), ('M', 'Male')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_image',
            field=models.ImageField(blank='True', default='account/media/user_images/default.jpg', upload_to='account/media/user_images'),
        ),
    ]
