# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 20:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_posted', models.DateTimeField(default=datetime.datetime(2016, 6, 3, 13, 40, 37, 546000))),
                ('comment_text', models.TextField(max_length=2000)),
                ('comment_favorited', models.IntegerField(default=0)),
                ('comment_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Points_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_comment_isFavorited', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1, null=True)),
                ('points_comment_vote', models.CharField(choices=[('D', 'Dislike'), ('N', 'No vote'), ('L', 'Like')], default='N', max_length=1)),
                ('points_comment_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Points_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_post_isFavorited', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1, null=True)),
                ('points_post_vote', models.CharField(choices=[('D', 'Dislike'), ('N', 'No vote'), ('L', 'Like')], default='N', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_posted', models.DateTimeField(default=datetime.datetime(2016, 6, 3, 13, 40, 37, 545000))),
                ('post_text', models.TextField(max_length=2000)),
                ('post_points', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_favorited', models.IntegerField(default=0)),
                ('post_image', models.ImageField(upload_to=b'')),
                ('post_tags', models.CharField(default=None, max_length=1000)),
                ('post_IsAdvertised', models.BooleanField(default='false')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='points_post',
            name='points_post_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='points_post',
            name='points_post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='points_comment',
            name='points_comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='points_comment',
            name='points_comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
