# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.CharField(default='Anonymus', max_length=40),
        ),
    ]
