# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GalleryPost_image', models.ImageField(height_field=300, upload_to=b'', width_field=300)),
                ('GalleryPost_tags', models.CharField(max_length=250)),
                ('GalleryPost_title', models.CharField(max_length=250)),
            ],
        ),
    ]
