# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160603_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_test',
            new_name='post_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 13, 44, 57, 96000)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 13, 44, 57, 96000)),
        ),
    ]
