# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160518_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post/static/post/images'),
        ),
    ]
