# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160518_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_posted', models.DateTimeField(verbose_name='DateTime published')),
                ('comment_text', models.TextField(max_length=2000)),
                ('comment_likes', models.IntegerField(default=0)),
                ('comment_views', models.IntegerField(default=0)),
                ('comment_favorited', models.IntegerField(default=0)),
                ('comment_dislikes', models.IntegerField(default=0)),
                ('comment_user', models.CharField(default='Anonymus', max_length=40)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
