# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_IsAdvertised',
            field=models.BooleanField(default='false'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_points',
            field=models.IntegerField(default=0),
        ),
    ]
