# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20160526_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
