# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20160522_2051'),
        ('post', '0010_auto_20160526_0958'),
    ]

    operations = [
    ]
