# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='GalleryPost_image',
            field=models.FileField(upload_to=b''),
        ),
    ]
