# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_auto_20160526_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_user',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
