# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20160526_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.CharField(default='Anonymus', max_length=40),
        ),
    ]
