# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_points_comment_points_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points_comment',
            name='points_comment_vote',
            field=models.CharField(choices=[('D', 'Dislike'), ('L', 'Like')], max_length=1, null=True),
        ),
    ]
