# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20160530_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='points_comment',
            name='points_comment_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 8, 53, 8, 509000)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_posted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 8, 53, 8, 508000)),
        ),
    ]
